namespace TrashMobMobile.Tests.ViewModels;

using Moq;
using TrashMobMobile.Models;
using TrashMobMobile.Services;
using TrashMobMobile.ViewModels;
using Xunit;

public class NewsletterPreferencesViewModelTests
{
    private readonly Mock<INewsletterPreferenceManager> mockManager;
    private readonly Mock<INotificationService> mockNotificationService;
    private readonly NewsletterPreferencesViewModel sut;

    public NewsletterPreferencesViewModelTests()
    {
        mockManager = new Mock<INewsletterPreferenceManager>();
        mockNotificationService = new Mock<INotificationService>();

        sut = new NewsletterPreferencesViewModel(
            mockManager.Object,
            mockNotificationService.Object);
    }

    [Fact]
    public async Task Init_LoadsPreferences()
    {
        // Arrange
        SetupDefaultMocks(count: 3);

        // Act
        await sut.Init();

        // Assert
        Assert.Equal(3, sut.Preferences.Count);
        Assert.True(sut.ArePreferencesFound);
        Assert.False(sut.AreNoPreferencesFound);
    }

    [Fact]
    public async Task Init_WithNoPreferences_ShowsEmptyState()
    {
        // Arrange
        SetupDefaultMocks(count: 0);

        // Act
        await sut.Init();

        // Assert
        Assert.Empty(sut.Preferences);
        Assert.False(sut.ArePreferencesFound);
        Assert.True(sut.AreNoPreferencesFound);
    }

    [Fact]
    public async Task Init_MapsPreferenceFieldsCorrectly()
    {
        // Arrange
        var preferences = new List<NewsletterPreferenceDto>
        {
            new()
            {
                CategoryId = 1,
                CategoryName = "Weekly Digest",
                CategoryDescription = "Weekly summary of events",
                IsSubscribed = true,
            },
        };

        mockManager.Setup(m => m.GetMyPreferencesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(preferences);

        // Act
        await sut.Init();

        // Assert
        var item = sut.Preferences[0];
        Assert.Equal(1, item.CategoryId);
        Assert.Equal("Weekly Digest", item.CategoryName);
        Assert.Equal("Weekly summary of events", item.CategoryDescription);
        Assert.True(item.IsSubscribed);
    }

    [Fact]
    public async Task TogglePreference_TogglesSubscriptionAndCallsApi()
    {
        // Arrange
        SetupDefaultMocks(count: 2);
        await sut.Init();

        var item = sut.Preferences[0];
        var originalValue = item.IsSubscribed;

        mockManager.Setup(m => m.UpdatePreferenceAsync(
                item.CategoryId, !originalValue, It.IsAny<CancellationToken>()))
            .Returns(Task.CompletedTask);

        // Act
        await sut.TogglePreferenceCommand.ExecuteAsync(item);

        // Assert
        Assert.Equal(!originalValue, item.IsSubscribed);
        mockManager.Verify(m => m.UpdatePreferenceAsync(
            item.CategoryId, !originalValue, It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task TogglePreference_WithNull_DoesNothing()
    {
        // Arrange
        SetupDefaultMocks(count: 1);
        await sut.Init();

        // Act
        await sut.TogglePreferenceCommand.ExecuteAsync(null);

        // Assert
        mockManager.Verify(m => m.UpdatePreferenceAsync(
            It.IsAny<int>(), It.IsAny<bool>(), It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task Init_CallsGetMyPreferencesAsync()
    {
        // Arrange
        SetupDefaultMocks(count: 0);

        // Act
        await sut.Init();

        // Assert
        mockManager.Verify(m => m.GetMyPreferencesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public void UnsubscribeAllCommand_Exists()
    {
        // Assert — verify the command was generated by RelayCommand
        Assert.NotNull(sut.UnsubscribeAllCommand);
    }

    private void SetupDefaultMocks(int count = 3)
    {
        var preferences = new List<NewsletterPreferenceDto>();

        for (var i = 0; i < count; i++)
        {
            preferences.Add(new NewsletterPreferenceDto
            {
                CategoryId = i + 1,
                CategoryName = $"Category {i + 1}",
                CategoryDescription = $"Description for category {i + 1}",
                IsSubscribed = i % 2 == 0,
            });
        }

        mockManager.Setup(m => m.GetMyPreferencesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(preferences);

        mockManager.Setup(m => m.UpdatePreferenceAsync(
                It.IsAny<int>(), It.IsAny<bool>(), It.IsAny<CancellationToken>()))
            .Returns(Task.CompletedTask);

        mockManager.Setup(m => m.UnsubscribeAllAsync(It.IsAny<CancellationToken>()))
            .Returns(Task.CompletedTask);
    }
}
