"""Centralized configuration for TrashMob Google Ad Grants account setup."""

from datetime import date

# --- Account ---
CUSTOMER_ID = "4587308084"
SITE_URL = "https://www.trashmob.eco"
STATE_FILE = "state.json"

# --- Geo targets (Google Ads geo target constant IDs) ---
GEO_TARGET_US = 2840
GEO_TARGET_WA = 21137
GEO_TARGET_OR = 21155

# --- Budget ---
DAILY_BUDGET_MICROS = 100_000_000  # $100/day per campaign

# --- Conversion actions ---
CONVERSION_ACTIONS = [
    {
        "name": "Volunteer Account Created",
        "category": "SIGNUP",
        "counting_type": "ONE_PER_CLICK",
    },
    {
        "name": "Event RSVP Completed",
        "category": "SIGNUP",
        "counting_type": "ONE_PER_CLICK",
    },
    {
        "name": "City Partner Inquiry",
        "category": "SUBMIT_LEAD_FORM",
        "counting_type": "ONE_PER_CLICK",
    },
    {
        "name": "Event Created by Organizer",
        "category": "SIGNUP",
        "counting_type": "ONE_PER_CLICK",
    },
]

# --- Negative keywords (campaign-level, applied to all campaigns) ---
NEGATIVE_KEYWORDS = [
    "jobs",
    "career",
    "salary",
    "hiring",
    "employment",
    "free stuff",
    "free items",
    "giveaway",
    "how to litter",
    "trash can",
    "trash bag",
    "trash bin",
    "dumpster",
    "junk removal",
    "waste management company",
]

# --- Sitelinks (shared across campaigns, assigned per campaign) ---
SITELINKS = {
    "find_events": {
        "link_text": "Find Cleanup Events",
        "description1": "Search for litter cleanup events",
        "description2": "happening near you this week.",
        "final_url": f"{SITE_URL}/volunteeropportunities",
    },
    "about": {
        "link_text": "About TrashMob",
        "description1": "Learn about our mission to",
        "description2": "clean up communities together.",
        "final_url": f"{SITE_URL}/aboutus",
    },
    "getting_started": {
        "link_text": "Getting Started",
        "description1": "Create your first cleanup event",
        "description2": "in just a few minutes.",
        "final_url": f"{SITE_URL}/gettingstarted",
    },
    "communities": {
        "link_text": "For Communities",
        "description1": "City and municipal partnership",
        "description2": "programs for litter management.",
        "final_url": f"{SITE_URL}/for-communities",
    },
    "partnerships": {
        "link_text": "Partner With Us",
        "description1": "Sponsor cleanups and support",
        "description2": "your local community.",
        "final_url": f"{SITE_URL}/partnerships",
    },
    "leaderboards": {
        "link_text": "Leaderboards",
        "description1": "See top volunteers and teams",
        "description2": "making an impact.",
        "final_url": f"{SITE_URL}/leaderboards",
    },
    "contact": {
        "link_text": "Contact Us",
        "description1": "Get in touch with the",
        "description2": "TrashMob team.",
        "final_url": f"{SITE_URL}/contactus",
    },
    "litter_reports": {
        "link_text": "Report Litter",
        "description1": "Spotted litter in your area?",
        "description2": "Report it so volunteers can help.",
        "final_url": f"{SITE_URL}/litterreports",
    },
}

# --- Campaigns, ad groups, keywords, ads, and sitelink assignments ---
CAMPAIGNS = [
    {
        "name": "TrashMob Brand Campaign",
        "geo_targets": [GEO_TARGET_US],
        "sitelinks": ["find_events", "about", "getting_started", "leaderboards"],
        "ad_groups": [
            {
                "name": "Brand - Core",
                "keywords": [
                    ("trashmob volunteer", "PHRASE"),
                    ("trashmob litter cleanup", "PHRASE"),
                    ("trashmob.eco events", "PHRASE"),
                    ("trashmob community cleanup", "PHRASE"),
                    ("trash mob eco", "PHRASE"),
                    ("trashmob app", "PHRASE"),
                ],
                "rsa": {
                    "final_url": f"{SITE_URL}/",
                    "path1": "volunteer",
                    "path2": "",
                    "headlines": [
                        "TrashMob.eco",
                        "Join TrashMob Today",
                        "Free Cleanup Events",
                        "Meet Up. Clean Up.",
                        "Volunteer With TrashMob",
                        "Community Litter Cleanup",
                        "Feel Good Volunteering",
                        "Clean Up Your Community",
                        "Local Cleanup Events",
                        "Join a Cleanup Crew",
                        "Make a Difference Today",
                        "Sign Up in Minutes",
                        "501(c)(3) Nonprofit",
                        "No Cost to Participate",
                        "Thousands of Volunteers",
                    ],
                    "descriptions": [
                        "Find and join free litter cleanup events in your city. Sign up in minutes at TrashMob.eco.",
                        "Meet up. Clean up. Feel good. Join thousands of volunteers making communities cleaner.",
                        "TrashMob connects volunteers with local cleanup events. Free to join, easy to organize.",
                        "Cleaning up Planet Earth, one bucket of trash at a time. Together. Join TrashMob today.",
                    ],
                },
            },
            {
                "name": "Brand - Mission",
                "keywords": [
                    ("trashmob nonprofit", "PHRASE"),
                    ("trash mob cleanup events", "PHRASE"),
                    ("trashmob eco volunteer", "PHRASE"),
                    ("trashmob litter report", "PHRASE"),
                ],
                "rsa": {
                    "final_url": f"{SITE_URL}/aboutus",
                    "path1": "about",
                    "path2": "",
                    "headlines": [
                        "TrashMob.eco Mission",
                        "Why TrashMob Exists",
                        "Our Environmental Impact",
                        "Clean Communities Together",
                        "Volunteer-Powered Cleanups",
                        "Free Litter Cleanup Platform",
                        "Join the Movement",
                        "501(c)(3) Nonprofit Org",
                        "Built by Volunteers",
                        "Track Your Impact",
                        "Teams & Leaderboards",
                        "Community Cleanup Events",
                        "Report Litter Near You",
                        "Organize a Cleanup",
                        "Meet Up. Clean Up.",
                    ],
                    "descriptions": [
                        "TrashMob.eco is a 501(c)(3) nonprofit connecting volunteers with community litter cleanups.",
                        "Our mission: clean up Planet Earth one bucket of trash at a time. Together.",
                        "Free platform for organizing and joining litter cleanup events. No cost, big impact.",
                        "Join a growing community of environmental volunteers. Track impact, compete, and have fun.",
                    ],
                },
            },
        ],
    },
    {
        "name": "Volunteer Recruitment - Pacific NW",
        "geo_targets": [GEO_TARGET_WA, GEO_TARGET_OR],
        "sitelinks": ["find_events", "getting_started", "leaderboards", "litter_reports"],
        "ad_groups": [
            {
                "name": "Volunteer PNW - Cleanup Events",
                "keywords": [
                    ("community litter cleanup events near me", "BROAD"),
                    ("volunteer for trash cleanup", "BROAD"),
                    ("local environmental volunteer opportunities", "BROAD"),
                    ("join neighborhood cleanup crew", "BROAD"),
                    ("outdoor volunteer opportunities Washington", "BROAD"),
                    ("community service litter pickup", "BROAD"),
                    ("volunteer cleanup seattle", "PHRASE"),
                    ("community cleanup portland", "PHRASE"),
                ],
                "rsa": {
                    "final_url": f"{SITE_URL}/volunteeropportunities",
                    "path1": "volunteer",
                    "path2": "events",
                    "headlines": [
                        "Local Cleanup Events",
                        "Volunteer Near You",
                        "Free Community Cleanups",
                        "Join a Cleanup This Week",
                        "Help Clean Your City",
                        "Litter Cleanup Volunteers",
                        "Find Events in Your Area",
                        "Weekend Cleanup Events",
                        "Sign Up in 2 Minutes",
                        "No Experience Needed",
                        "Meet Local Volunteers",
                        "Make Your City Cleaner",
                        "Pacific NW Cleanups",
                        "Volunteer Outdoors",
                        "Feel Good Volunteering",
                    ],
                    "descriptions": [
                        "Find free litter cleanup events happening near you this week. Sign up in minutes at TrashMob.eco.",
                        "Join local volunteers making Pacific NW communities cleaner. No experience needed, just show up!",
                        "Looking for outdoor volunteer opportunities? Join a neighborhood cleanup event near you today.",
                        "Meet up with fellow volunteers. Clean up your community. Feel good about making a difference.",
                    ],
                },
            },
            {
                "name": "Volunteer PNW - Community Service",
                "keywords": [
                    ("community service volunteer hours", "BROAD"),
                    ("outdoor volunteer work near me", "BROAD"),
                    ("weekend volunteer opportunities", "BROAD"),
                    ("environmental volunteer groups near me", "BROAD"),
                    ("volunteer cleanup events Washington state", "BROAD"),
                    ("litter pickup volunteer Oregon", "BROAD"),
                ],
                "rsa": {
                    "final_url": f"{SITE_URL}/volunteeropportunities",
                    "path1": "volunteer",
                    "path2": "PNW",
                    "headlines": [
                        "Earn Volunteer Hours",
                        "Community Service Events",
                        "Weekend Volunteering",
                        "Outdoor Volunteer Work",
                        "Environmental Volunteering",
                        "Free Cleanup Events",
                        "Log Your Impact Hours",
                        "Join a Local Team",
                        "Group Volunteer Events",
                        "Family-Friendly Cleanups",
                        "Corporate Group Events",
                        "Track Your Contributions",
                        "Make a Real Difference",
                        "Community Cleanup Crew",
                        "Sign Up Free Today",
                    ],
                    "descriptions": [
                        "Need community service hours? Join a free litter cleanup event and make a real difference.",
                        "Weekend volunteer opportunities for individuals, families, and corporate groups. Sign up at TrashMob.eco.",
                        "Track your volunteer hours and environmental impact. Join cleanup events in Washington and Oregon.",
                        "Free outdoor volunteer events every week. Meet great people while cleaning up your community.",
                    ],
                },
            },
        ],
    },
    {
        "name": "Volunteer Recruitment - National",
        "geo_targets": [GEO_TARGET_US],
        "sitelinks": ["find_events", "getting_started", "about", "leaderboards"],
        "ad_groups": [
            {
                "name": "Volunteer National - General",
                "keywords": [
                    ("volunteer cleanup near me", "BROAD"),
                    ("community cleanup events", "BROAD"),
                    ("neighborhood cleanup volunteer", "BROAD"),
                    ("litter cleanup volunteer opportunities", "BROAD"),
                    ("environmental volunteer events", "BROAD"),
                    ("free volunteer events near me", "BROAD"),
                ],
                "rsa": {
                    "final_url": f"{SITE_URL}/volunteeropportunities",
                    "path1": "volunteer",
                    "path2": "events",
                    "headlines": [
                        "Find Cleanups Near You",
                        "Volunteer This Weekend",
                        "Free Cleanup Events",
                        "Join Local Volunteers",
                        "Community Litter Cleanup",
                        "Sign Up in Minutes",
                        "No Experience Needed",
                        "Help Clean Your City",
                        "Meet Fellow Volunteers",
                        "Make a Difference Today",
                        "Neighborhood Cleanups",
                        "Environmental Volunteer",
                        "Outdoor Volunteering",
                        "Track Your Impact",
                        "Feel Good Volunteering",
                    ],
                    "descriptions": [
                        "Find free litter cleanup events near you. Sign up in minutes and start making a difference.",
                        "Join thousands of volunteers across the US cleaning up their communities with TrashMob.eco.",
                        "No experience needed — just show up and help! Free community cleanup events every week.",
                        "Meet local volunteers, clean up litter, and track your environmental impact. Join TrashMob today.",
                    ],
                },
            },
            {
                "name": "Volunteer National - Community",
                "keywords": [
                    ("community service cleanup events", "BROAD"),
                    ("outdoor volunteer opportunities", "BROAD"),
                    ("group volunteer activities", "BROAD"),
                    ("family volunteer events near me", "BROAD"),
                    ("corporate volunteer cleanup", "BROAD"),
                    ("weekend community service", "BROAD"),
                ],
                "rsa": {
                    "final_url": f"{SITE_URL}/volunteeropportunities",
                    "path1": "events",
                    "path2": "cleanup",
                    "headlines": [
                        "Group Volunteer Events",
                        "Family-Friendly Cleanups",
                        "Corporate Team Building",
                        "Weekend Service Events",
                        "Community Service Hours",
                        "Outdoor Group Activities",
                        "Free Community Events",
                        "Cleanup With Your Team",
                        "Great for All Ages",
                        "Organize a Group Event",
                        "Fun Outdoor Volunteering",
                        "Build Team Spirit",
                        "Log Volunteer Hours",
                        "Meet New People",
                        "Join a Cleanup Crew",
                    ],
                    "descriptions": [
                        "Perfect for families, corporate teams, and community groups. Free cleanup events near you.",
                        "Looking for group volunteer activities? Organize or join a litter cleanup with TrashMob.eco.",
                        "Earn community service hours while making a real difference. Free events, no cost to join.",
                        "Team building that matters. Organize a cleanup for your group and track collective impact.",
                    ],
                },
            },
        ],
    },
    {
        "name": "City and Municipality Outreach",
        "geo_targets": [GEO_TARGET_US],
        "sitelinks": ["communities", "partnerships", "about", "contact"],
        "ad_groups": [
            {
                "name": "City Outreach - Programs",
                "keywords": [
                    ("adopt a street program software", "BROAD"),
                    ("litter cleanup volunteer management platform", "BROAD"),
                    ("municipal volunteer coordination tool", "BROAD"),
                    ("community cleanup event management", "BROAD"),
                    ("city litter abatement program", "BROAD"),
                    ("volunteer tracking software for cities", "BROAD"),
                ],
                "rsa": {
                    "final_url": f"{SITE_URL}/for-communities",
                    "path1": "communities",
                    "path2": "",
                    "headlines": [
                        "City Cleanup Programs",
                        "Volunteer Management Tool",
                        "Free for Municipalities",
                        "Adopt-a-Street Software",
                        "Litter Abatement Platform",
                        "Track Volunteer Impact",
                        "Community Partnership",
                        "Reduce Litter Complaints",
                        "Engage Local Volunteers",
                        "Automated Compliance",
                        "501(c)(3) Nonprofit",
                        "No Cost to Your City",
                        "Proven Cleanup Platform",
                        "Data-Driven Results",
                        "Request a Demo Today",
                    ],
                    "descriptions": [
                        "Free volunteer management platform for cities. Track cleanups, measure impact, engage residents.",
                        "TrashMob.eco helps municipalities run Adopt-a-Street programs with automated compliance tracking.",
                        "Reduce litter complaints with organized volunteer cleanups. Free platform, no cost to your city.",
                        "Join cities across the US using TrashMob to coordinate community cleanup programs. Contact us today.",
                    ],
                },
            },
            {
                "name": "City Outreach - Adopt a Location",
                "keywords": [
                    ("adopt a road program", "BROAD"),
                    ("adopt a park volunteer program", "BROAD"),
                    ("community litter prevention program", "BROAD"),
                    ("city volunteer cleanup coordination", "BROAD"),
                    ("municipal cleanup management software", "BROAD"),
                ],
                "rsa": {
                    "final_url": f"{SITE_URL}/for-communities",
                    "path1": "adopt",
                    "path2": "location",
                    "headlines": [
                        "Adopt-a-Location Program",
                        "Adopt a Road or Park",
                        "Automated Area Tracking",
                        "Volunteer Area Adoption",
                        "Ongoing Cleanup Commitment",
                        "Free Platform for Cities",
                        "Compliance Monitoring",
                        "Community Engagement Tool",
                        "Reduce Maintenance Costs",
                        "Empower Local Volunteers",
                        "Track Adopted Areas",
                        "Measurable Impact Data",
                        "Photo Documentation",
                        "Easy Volunteer Signup",
                        "Schedule Regular Cleanups",
                    ],
                    "descriptions": [
                        "Run Adopt-a-Road and Adopt-a-Park programs with automated compliance tracking. Free for cities.",
                        "Volunteers adopt areas for ongoing cleanup. Track schedules, photos, and compliance automatically.",
                        "Reduce park and road maintenance costs with organized volunteer adoption programs. Contact us.",
                        "TrashMob's area adoption feature lets volunteers commit to keeping specific locations clean.",
                    ],
                },
            },
        ],
    },
    {
        "name": "Event Organizer Recruitment",
        "geo_targets": [GEO_TARGET_US],
        "sitelinks": ["getting_started", "find_events", "leaderboards", "about"],
        "ad_groups": [
            {
                "name": "Organizers - Create Events",
                "keywords": [
                    ("how to organize a community cleanup", "BROAD"),
                    ("start a neighborhood cleanup event", "BROAD"),
                    ("free event management for nonprofits", "BROAD"),
                    ("litter cleanup event planning tool", "BROAD"),
                    ("organize volunteer cleanup event", "BROAD"),
                ],
                "rsa": {
                    "final_url": f"{SITE_URL}/gettingstarted",
                    "path1": "organize",
                    "path2": "cleanup",
                    "headlines": [
                        "Organize a Cleanup Event",
                        "Create an Event in Minutes",
                        "Free Event Planning Tool",
                        "Lead a Community Cleanup",
                        "Rally Your Neighbors",
                        "Easy Event Management",
                        "Recruit Volunteers Fast",
                        "Bulk Email Invitations",
                        "Track Event Metrics",
                        "Build Your Team",
                        "No Cost to Organize",
                        "Step-by-Step Guide",
                        "Automated Event Pages",
                        "Share on Social Media",
                        "Make an Impact Locally",
                    ],
                    "descriptions": [
                        "Create a litter cleanup event in minutes. Free tools to recruit volunteers and track results.",
                        "Everything you need to organize a community cleanup. Free platform, step-by-step guidance.",
                        "Start a neighborhood cleanup event today. TrashMob handles signups, reminders, and impact tracking.",
                        "Lead a cleanup crew in your community. Free event management tools for volunteer organizers.",
                    ],
                },
            },
            {
                "name": "Organizers - Volunteer Coordination",
                "keywords": [
                    ("volunteer event coordination software", "BROAD"),
                    ("manage cleanup volunteers", "BROAD"),
                    ("community event organizer tools", "BROAD"),
                    ("free volunteer management platform", "BROAD"),
                    ("track volunteer participation", "BROAD"),
                ],
                "rsa": {
                    "final_url": f"{SITE_URL}/gettingstarted",
                    "path1": "manage",
                    "path2": "volunteers",
                    "headlines": [
                        "Manage Your Volunteers",
                        "Free Coordination Tools",
                        "Track Participation",
                        "Send Bulk Invitations",
                        "Automated Reminders",
                        "Post-Event Reporting",
                        "Bags, Weight & Hours",
                        "Photo Documentation",
                        "Volunteer Leaderboards",
                        "Team Management",
                        "Event Summary Reports",
                        "Built for Organizers",
                        "No Technical Skills Needed",
                        "Mobile-Friendly Platform",
                        "Start Organizing Today",
                    ],
                    "descriptions": [
                        "Free tools to manage cleanup volunteers. Send invites, track attendance, and report impact.",
                        "TrashMob makes volunteer coordination easy. Automated reminders, RSVPs, and post-event reporting.",
                        "Track bags collected, weight, hours, and more. Generate impact reports for your organization.",
                        "Manage teams, send bulk invitations, and coordinate pickup locations. All free at TrashMob.eco.",
                    ],
                },
            },
        ],
    },
    {
        "name": "Community Partners and Sponsors",
        "geo_targets": [GEO_TARGET_US],
        "sitelinks": ["partnerships", "communities", "about", "contact"],
        "ad_groups": [
            {
                "name": "Partners - Nonprofit Cleanup",
                "keywords": [
                    ("nonprofit community cleanup partner", "BROAD"),
                    ("environmental nonprofit partnership", "BROAD"),
                    ("community cleanup sponsorship", "BROAD"),
                    ("corporate volunteer program partner", "BROAD"),
                    ("litter cleanup nonprofit organization", "BROAD"),
                ],
                "rsa": {
                    "final_url": f"{SITE_URL}/partnerships",
                    "path1": "partner",
                    "path2": "",
                    "headlines": [
                        "Partner With TrashMob",
                        "Community Cleanup Partner",
                        "Environmental Partnership",
                        "Sponsor Local Cleanups",
                        "Corporate CSR Programs",
                        "Brand Visibility at Events",
                        "501(c)(3) Tax Deductible",
                        "Support Clean Communities",
                        "Employee Volunteer Events",
                        "Measurable Social Impact",
                        "Custom Partnership Plans",
                        "National Nonprofit Partner",
                        "Local Event Sponsorship",
                        "Co-Branded Cleanup Events",
                        "Contact Us Today",
                    ],
                    "descriptions": [
                        "Partner with TrashMob.eco to sponsor community litter cleanups. Tax-deductible, measurable impact.",
                        "Support clean communities through corporate sponsorship. Brand visibility at local cleanup events.",
                        "Custom partnership programs for businesses and organizations. Contact the TrashMob team today.",
                        "Corporate volunteer programs, event sponsorship, and community engagement. Partner with TrashMob.",
                    ],
                },
            },
            {
                "name": "Partners - Environmental Giving",
                "keywords": [
                    ("donate to environmental nonprofit", "BROAD"),
                    ("support community cleanup organization", "BROAD"),
                    ("environmental charity volunteer", "BROAD"),
                    ("litter prevention nonprofit donate", "BROAD"),
                    ("community cleanup tax deductible donation", "BROAD"),
                ],
                "rsa": {
                    "final_url": f"{SITE_URL}/partnerships",
                    "path1": "support",
                    "path2": "us",
                    "headlines": [
                        "Support TrashMob.eco",
                        "Tax-Deductible Donations",
                        "Fund Clean Communities",
                        "Environmental Giving",
                        "501(c)(3) Nonprofit",
                        "Every Dollar Counts",
                        "Support Local Cleanups",
                        "Donate to TrashMob",
                        "Help Clean Up America",
                        "Your Gift Makes Impact",
                        "Transparent Impact Data",
                        "Support Volunteers",
                        "Litter-Free Communities",
                        "Give to the Environment",
                        "Change Starts Locally",
                    ],
                    "descriptions": [
                        "Support TrashMob.eco with a tax-deductible donation. Every dollar helps fund community cleanups.",
                        "Your donation supports thousands of volunteers cleaning up communities across the United States.",
                        "Help us keep communities clean. TrashMob.eco is a 501(c)(3) nonprofit. All donations are tax-deductible.",
                        "Fund the movement. TrashMob volunteers have cleaned up millions of pounds of litter. Support us today.",
                    ],
                },
            },
        ],
    },
]

# --- Landing page URLs for reference ---
LANDING_PAGES = {
    "home": f"{SITE_URL}/",
    "volunteer": f"{SITE_URL}/volunteeropportunities",
    "about": f"{SITE_URL}/aboutus",
    "getting_started": f"{SITE_URL}/gettingstarted",
    "communities": f"{SITE_URL}/for-communities",
    "partnerships": f"{SITE_URL}/partnerships",
    "leaderboards": f"{SITE_URL}/leaderboards",
    "contact": f"{SITE_URL}/contactus",
    "litter_reports": f"{SITE_URL}/litterreports",
    "faq": f"{SITE_URL}/faq",
}
