import { test as base, Page, BrowserContext, expect } from '@playwright/test';
import path from 'path';
import fs from 'fs';

// Path to stored auth state (generated by global-setup.ts)
const AUTH_STATE_DIR = path.join(__dirname, '..', '.auth');
export const USER_AUTH_FILE = path.join(AUTH_STATE_DIR, 'user.json');
export const ADMIN_AUTH_FILE = path.join(AUTH_STATE_DIR, 'admin.json');

function hasAuthState(filePath: string): boolean {
    return fs.existsSync(filePath);
}

interface AuthState {
    sessionStorage?: Record<string, string>;
    sessionStorageOrigin?: string;
}

/**
 * Restores sessionStorage (where MSAL stores tokens) into the page.
 * Must be called after navigating to the app origin.
 */
async function restoreSessionStorage(page: Page, authFile: string): Promise<void> {
    const state: AuthState = JSON.parse(fs.readFileSync(authFile, 'utf-8'));
    if (!state.sessionStorage || Object.keys(state.sessionStorage).length === 0) return;

    await page.evaluate((data) => {
        for (const [key, value] of Object.entries(data)) {
            sessionStorage.setItem(key, value);
        }
    }, state.sessionStorage);
}

/**
 * Creates an authenticated page: loads cookies/localStorage via storageState,
 * then restores MSAL sessionStorage and reloads so the app picks up the session.
 */
async function createAuthenticatedPage(browser: import('@playwright/test').Browser, authFile: string): Promise<{ page: Page; context: BrowserContext }> {
    const context = await browser.newContext({
        storageState: authFile,
    });
    const page = await context.newPage();

    // Navigate to a lightweight page first (needed to set sessionStorage on the right domain)
    // Avoid the home page which can crash if v2 paginated responses aren't handled yet
    const state: AuthState = JSON.parse(fs.readFileSync(authFile, 'utf-8'));
    const origin = state.sessionStorageOrigin || 'https://dev.trashmob.eco';
    await page.goto(`${origin}/aboutus`, { waitUntil: 'commit' });

    // Inject MSAL sessionStorage
    await restoreSessionStorage(page, authFile);

    // Reload so MSAL picks up the restored tokens
    await page.reload({ waitUntil: 'domcontentloaded' });
    // Brief wait for MSAL to initialize from restored sessionStorage
    await page.waitForTimeout(2000);

    return { page, context };
}

/**
 * Extended test fixture with authenticated page support.
 *
 * Usage:
 * ```typescript
 * import { test, expect } from '../fixtures/auth.fixture';
 *
 * test('authenticated test', async ({ authenticatedPage }) => {
 *   await authenticatedPage.goto('/mydashboard');
 * });
 * ```
 */
export const test = base.extend<{
    authenticatedPage: Page;
    authenticatedContext: BrowserContext;
    adminPage: Page;
}>({
    authenticatedPage: async ({ browser }, use, testInfo) => {
        if (!hasAuthState(USER_AUTH_FILE)) {
            testInfo.skip(true, 'No auth state — set E2E_USER_EMAIL/E2E_USER_PASSWORD to enable');
            return;
        }
        const { page, context } = await createAuthenticatedPage(browser, USER_AUTH_FILE);
        await use(page);
        await context.close();
    },

    authenticatedContext: async ({ browser }, use, testInfo) => {
        if (!hasAuthState(USER_AUTH_FILE)) {
            testInfo.skip(true, 'No auth state — set E2E_USER_EMAIL/E2E_USER_PASSWORD to enable');
            return;
        }
        const context = await browser.newContext({
            storageState: USER_AUTH_FILE,
        });
        await use(context);
        await context.close();
    },

    adminPage: async ({ browser }, use, testInfo) => {
        if (!hasAuthState(ADMIN_AUTH_FILE)) {
            testInfo.skip(true, 'No admin auth state — set E2E_ADMIN_EMAIL/E2E_ADMIN_PASSWORD to enable');
            return;
        }
        const { page, context } = await createAuthenticatedPage(browser, ADMIN_AUTH_FILE);
        await use(page);
        await context.close();
    },
});

export { expect };
