// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrashMob.Shared.Persistence;

#nullable disable

namespace TrashMob.Migrations
{
    [DbContext(typeof(MobDbContext))]
    [Migration("20220927042847_AddPartnerRequestFields")]
    partial class AddPartnerRequestFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TrashMob.Models.ContactRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Message")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.ToTable("ContactRequests");
                });

            modelBuilder.Entity("TrashMob.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EventStatusId")
                        .HasColumnType("int");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEventPublic")
                        .HasColumnType("bit");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int?>("MaxNumberOfParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EventStatusId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("TrashMob.Models.EventAttendee", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CanceledDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("SignUpDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("EventAttendees");
                });

            modelBuilder.Entity("TrashMob.Models.EventPartner", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartnerLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EventPartnerStatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EventId", "PartnerId", "PartnerLocationId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EventPartnerStatusId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("PartnerLocationId");

                    b.ToTable("EventPartners");
                });

            modelBuilder.Entity("TrashMob.Models.EventPartnerStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EventPartnerStatuses");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Partner has not been contacted",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "None"
                        },
                        new
                        {
                            Id = 1,
                            Description = "Request is awaiting processing by partner",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Requested"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Request has been approved by partner",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Accepted"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Request has been declined by partner",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Declined"
                        });
                });

            modelBuilder.Entity("TrashMob.Models.EventStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EventStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Event is actively recruiting new members",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Event is full",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Full"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Event has been canceled",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Canceled"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Event has completed",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("TrashMob.Models.EventSummary", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActualNumberOfAttendees")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("NumberOfBags")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBuckets")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.ToTable("EventSummaries");
                });

            modelBuilder.Entity("TrashMob.Models.EventType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EventTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Park Cleanup",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Park Cleanup"
                        },
                        new
                        {
                            Id = 2,
                            Description = "School Cleanup",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "School Cleanup"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Neighborhood Cleanup",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Neighborhood Cleanup"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Beach Cleanup",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Beach Cleanup"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Highway Cleanup",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Highway Cleanup"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Natural Disaster Cleanup",
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "Natural Disaster Cleanup"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Trail Cleanup",
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "Trail Cleanup"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Reef Cleanup",
                            DisplayOrder = 8,
                            IsActive = true,
                            Name = "Reef Cleanup"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Private Land Cleanup",
                            DisplayOrder = 9,
                            IsActive = true,
                            Name = "Private Land Cleanup"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Dog Park Cleanup",
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Dog Park Cleanup"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Waterway Cleanup",
                            DisplayOrder = 11,
                            IsActive = true,
                            Name = "Waterway Cleanup"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Vandalism Cleanup",
                            DisplayOrder = 12,
                            IsActive = true,
                            Name = "Vandalism Cleanup"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Social Event",
                            DisplayOrder = 13,
                            IsActive = true,
                            Name = "Social Event"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Other",
                            DisplayOrder = 14,
                            IsActive = true,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("TrashMob.Models.MessageRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Message")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.ToTable("MessageRequests");
                });

            modelBuilder.Entity("TrashMob.Models.NonEventUserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserNotificationTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserNotificationTypeId");

                    b.ToTable("NonEventUserNotifications");
                });

            modelBuilder.Entity("TrashMob.Models.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("PartnerStatusId")
                        .HasColumnType("int");

                    b.Property<int>("PartnerTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrivateNotes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PublicNotes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("PartnerStatusId");

                    b.HasIndex("PartnerTypeId");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PartnerContactTypeId")
                        .HasColumnType("int");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("PartnerId");

                    b.ToTable("PartnerContacts");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("PartnerId");

                    b.ToTable("PartnerDocuments");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PrimaryEmail")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PrimaryPhone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PrivateNotes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PublicNotes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SecondaryEmail")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SecondaryPhone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("PartnerId");

                    b.ToTable("PartnerLocations");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerLocationService", b =>
                {
                    b.Property<Guid>("PartnerLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PartnerLocationId", "ServiceTypeId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("PartnerLocationServices");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Country")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("PartnerRequestStatusId")
                        .HasColumnType("int");

                    b.Property<int>("PartnerTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Region")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isBecomeAPartnerRequest")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("PartnerRequestStatusId");

                    b.HasIndex("PartnerTypeId");

                    b.ToTable("PartnerRequests");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerRequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PartnerRequestStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Request is Pending Approval by Site Administrator",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Request has been approved by the Site Administrator",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Request has been approved by the Site Administrator",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Denied"
                        });
                });

            modelBuilder.Entity("TrashMob.Models.PartnerService", b =>
                {
                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartnerId", "ServiceTypeId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("PartnerServices");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerSocialMediaAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountIdentifier")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SocialMediaAccountTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("SocialMediaAccountTypeId");

                    b.ToTable("PartnerSocialMediaAccounts");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PartnerStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Partner is Active",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Partner is Inactive",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Inactive"
                        });
                });

            modelBuilder.Entity("TrashMob.Models.PartnerType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PartnerTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Partner is a Government or Government Agency",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Government"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Partner is Business",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Business"
                        });
                });

            modelBuilder.Entity("TrashMob.Models.PartnerUser", b =>
                {
                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("PartnerId", "UserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("PartnerUsers");
                });

            modelBuilder.Entity("TrashMob.Models.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Partner will haul litter away",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Hauling"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Partner will dispose of litter",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Disposal Location"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Partner distributes starter kits",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Startup Kits"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Partner distributes supplies",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Supplies"
                        });
                });

            modelBuilder.Entity("TrashMob.Models.SiteMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("MetricValue")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ProcessedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.ToTable("SiteMetrics");
                });

            modelBuilder.Entity("TrashMob.Models.SocialMediaAccountType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SocialMediaAccountTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Facebook",
                            DisplayOrder = 1,
                            Name = "Facebook"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Twitter",
                            DisplayOrder = 2,
                            Name = "Twitter"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Instagram",
                            DisplayOrder = 3,
                            Name = "Instagram"
                        },
                        new
                        {
                            Id = 4,
                            Description = "TikTok",
                            DisplayOrder = 4,
                            Name = "TikTok"
                        });
                });

            modelBuilder.Entity("TrashMob.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateAgreedToPrivacyPolicy")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateAgreedToTermsOfService")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateAgreedToTrashMobWaiver")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("GivenName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsSiteAdmin")
                        .HasColumnType("bit");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("MemberSince")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NameIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("PrefersMetric")
                        .HasColumnType("bit");

                    b.Property<string>("PrivacyPolicyVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceSystemUserName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SurName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TermsOfServiceVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrashMobWaiverVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TravelLimitForLocalEvents")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            City = "Anytown",
                            Country = "AnyCountry",
                            CreatedByUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "info@trashmob.eco",
                            GivenName = "TrashMob",
                            IsSiteAdmin = false,
                            LastUpdatedByUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PrefersMetric = false,
                            Region = "AnyState",
                            SurName = "Eco",
                            TravelLimitForLocalEvents = 0,
                            UserName = "TrashMob"
                        });
                });

            modelBuilder.Entity("TrashMob.Models.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserNotificationTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EventId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserNotificationTypeId");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("TrashMob.Models.UserNotificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UserNotificationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Opt out of Post Event Summary",
                            DisplayOrder = 1,
                            Name = "EventSummaryAttendee"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Opt out of Event Summary Reminder for events you have lead",
                            DisplayOrder = 2,
                            Name = "EventSummaryHostReminder"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Opt out of notifications for events upcoming this week you are attending",
                            DisplayOrder = 3,
                            Name = "UpcomingEventAttendingThisWeek"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Opt out of notifications for events happening soon you are attending",
                            DisplayOrder = 4,
                            Name = "UpcomingEventAttendingSoon"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Opt out of notifications for events upcoming this week you are leading",
                            DisplayOrder = 5,
                            Name = "UpcomingEventHostingThisWeek"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Opt out of notifications for events happening soon you are leading",
                            DisplayOrder = 6,
                            Name = "UpcomingEventHostingSoon"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Opt out of notification for new events upcoming in your area this week",
                            DisplayOrder = 7,
                            Name = "UpcomingEventsInYourAreaThisWeek"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Opt out of notification for new events happening in your area soon",
                            DisplayOrder = 8,
                            Name = "UpcomingEventsInYourAreaSoon"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Opt out of Event Summary Week Reminder for events you have lead",
                            DisplayOrder = 9,
                            Name = "EventSummaryHostWeekReminder"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Opt out of notifications for User Profile Location",
                            DisplayOrder = 10,
                            Name = "UserProfileUpdateLocation"
                        });
                });

            modelBuilder.Entity("TrashMob.Models.ContactRequest", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("ContactRequestsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_ContactRequests_User_CreatedBy");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("ContactRequestsUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_ContactRequests_User_LastUpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");
                });

            modelBuilder.Entity("TrashMob.Models.Event", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("EventsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Events_ApplicationUser_CreatedBy");

                    b.HasOne("TrashMob.Models.EventStatus", "EventStatus")
                        .WithMany("Events")
                        .HasForeignKey("EventStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Events_EventStatuses");

                    b.HasOne("TrashMob.Models.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Events_EventTypes");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("EventsUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Events_ApplicationUser_LastUpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("EventStatus");

                    b.Navigation("EventType");

                    b.Navigation("LastUpdatedByUser");
                });

            modelBuilder.Entity("TrashMob.Models.EventAttendee", b =>
                {
                    b.HasOne("TrashMob.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_EventAttendees_Events");

                    b.HasOne("TrashMob.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_EventAttendees_ApplicationUser");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrashMob.Models.EventPartner", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("EventPartnersCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_EventPartners_User_CreatedBy");

                    b.HasOne("TrashMob.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_EventPartners_Events");

                    b.HasOne("TrashMob.Models.EventPartnerStatus", "EventPartnerStatus")
                        .WithMany("EventPartners")
                        .HasForeignKey("EventPartnerStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EventPartners_EventPartnerStatuses");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("EventPartnersUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_EventPartners_User_LastUpdatedBy");

                    b.HasOne("TrashMob.Models.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .IsRequired()
                        .HasConstraintName("FK_EventPartners_Partners");

                    b.HasOne("TrashMob.Models.PartnerLocation", "PartnerLocation")
                        .WithMany()
                        .HasForeignKey("PartnerLocationId")
                        .IsRequired()
                        .HasConstraintName("FK_EventPartners_PartnerLocations");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Event");

                    b.Navigation("EventPartnerStatus");

                    b.Navigation("LastUpdatedByUser");

                    b.Navigation("Partner");

                    b.Navigation("PartnerLocation");
                });

            modelBuilder.Entity("TrashMob.Models.EventSummary", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("EventSummariesCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_EventSummaries_User_CreatedBy");

                    b.HasOne("TrashMob.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_EventSummary_Events");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("EventSummariesUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_EventSummaries_User_LastUpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Event");

                    b.Navigation("LastUpdatedByUser");
                });

            modelBuilder.Entity("TrashMob.Models.MessageRequest", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("MessageRequestsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_MessageRequests_CreatedByUser_Id");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("MessageRequestsUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_MessageRequests_LastUpdatedByUser_Id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");
                });

            modelBuilder.Entity("TrashMob.Models.NonEventUserNotification", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("NonEventUserNotificationsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_NonEventUserNotification_CreatedByUser_Id");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("NonEventUserNotificationsUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_NonEventUserNotification_LastUpdatedByUser_Id");

                    b.HasOne("TrashMob.Models.User", "User")
                        .WithMany("NonEventUserNotifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_NonEventUserNotifications_User_Id");

                    b.HasOne("TrashMob.Models.UserNotificationType", "UserNotificationType")
                        .WithMany("NonEventUserNotifications")
                        .HasForeignKey("UserNotificationTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_NonEventUserNotifications_UserNotificationTypes");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");

                    b.Navigation("User");

                    b.Navigation("UserNotificationType");
                });

            modelBuilder.Entity("TrashMob.Models.Partner", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("PartnersCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Partners_CreatedByUser_Id");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("PartnersUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Partners_LastUpdatedByUser_Id");

                    b.HasOne("TrashMob.Models.PartnerStatus", "PartnerStatus")
                        .WithMany("Partners")
                        .HasForeignKey("PartnerStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Partners_PartnerStatus");

                    b.HasOne("TrashMob.Models.PartnerType", "PartnerType")
                        .WithMany("Partners")
                        .HasForeignKey("PartnerTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Partners_PartnerType");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");

                    b.Navigation("PartnerStatus");

                    b.Navigation("PartnerType");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerContact", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("PartnerContactsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerContacts_User_CreatedBy");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("PartnerContactsUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerContacts_User_LastUpdatedBy");

                    b.HasOne("TrashMob.Models.Partner", "Partner")
                        .WithMany("PartnerContacts")
                        .HasForeignKey("PartnerId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerContacts_Partner");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerDocument", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("PartnerDocumentsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerDocuments_User_CreatedBy");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("PartnerDocumentsUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerDocuments_User_LastUpdatedBy");

                    b.HasOne("TrashMob.Models.Partner", "Partner")
                        .WithMany("PartnerDocuments")
                        .HasForeignKey("PartnerId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerDocuments_Partner");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerLocation", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("PartnerLocationsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerLocations_CreatedByUser_Id");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("PartnerLocationsUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerLocations_LastUpdatedByUser_Id");

                    b.HasOne("TrashMob.Models.Partner", "Partner")
                        .WithMany("PartnerLocations")
                        .HasForeignKey("PartnerId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerLocations_Partners");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerLocationService", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("PartnerLocationServicesCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnersLocationServices_User_CreatedBy");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("PartnerLocationServicesUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerLocationServices_User_LastUpdatedBy");

                    b.HasOne("TrashMob.Models.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId");

                    b.HasOne("TrashMob.Models.PartnerLocation", "PartnerLocation")
                        .WithMany()
                        .HasForeignKey("PartnerLocationId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnersLocationService_PartnerLocations");

                    b.HasOne("TrashMob.Models.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerLocationService_ServiceTypes");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");

                    b.Navigation("Partner");

                    b.Navigation("PartnerLocation");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerRequest", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("PartnerRequestsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerRequests_CreatedByUser_Id");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("PartnerRequestsUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerRequests_LastUpdatedByUser_Id");

                    b.HasOne("TrashMob.Models.PartnerRequestStatus", "PartnerRequestStatus")
                        .WithMany("PartnerRequests")
                        .HasForeignKey("PartnerRequestStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerRequests_PartnerRequestStatus");

                    b.HasOne("TrashMob.Models.PartnerType", "PartnerType")
                        .WithMany("PartnerRequests")
                        .HasForeignKey("PartnerTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerRequests_PartnerType");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");

                    b.Navigation("PartnerRequestStatus");

                    b.Navigation("PartnerType");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerService", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("PartnerServicesCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerServices_User_CreatedBy");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("PartnerServicesUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerServices_User_LastUpdatedBy");

                    b.HasOne("TrashMob.Models.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerServices_Partners");

                    b.HasOne("TrashMob.Models.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerServices_ServiceTypes");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");

                    b.Navigation("Partner");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerSocialMediaAccount", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("PartnerSocialMediaAccountsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerSocialMediaAccount_CreatedByUser_Id");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("PartnerSocialMediaAccountsUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerSocialMediaAccount_LastUpdatedByUser_Id");

                    b.HasOne("TrashMob.Models.Partner", "Partner")
                        .WithMany("PartnerSocialMediaAccounts")
                        .HasForeignKey("PartnerId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerSocialMediaAccount_Partner");

                    b.HasOne("TrashMob.Models.SocialMediaAccountType", "SocialMediaAccountType")
                        .WithMany("PartnerSocialMediaAccounts")
                        .HasForeignKey("SocialMediaAccountTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerSocialMediaAccounts_SocialMediaAccountType");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");

                    b.Navigation("Partner");

                    b.Navigation("SocialMediaAccountType");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerUser", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("PartnerUsersCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerUsers_CreatedByUser_Id");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("PartnerUsersUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerUsers_LastUpdatedByUser_Id");

                    b.HasOne("TrashMob.Models.Partner", "Partner")
                        .WithMany("PartnerUsers")
                        .HasForeignKey("PartnerId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerUser_Partners");

                    b.HasOne("TrashMob.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_PartnerUser_User");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");

                    b.Navigation("Partner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrashMob.Models.SiteMetric", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("SiteMetricsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_SiteMetrics_CreatedByUser_Id");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("SiteMetricsUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_SiteMetrics_LastUpdatedByUser_Id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");
                });

            modelBuilder.Entity("TrashMob.Models.User", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("UsersCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_User_CreatedByUser_Id");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("UsersUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_User_LastUpdatedByUser_Id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");
                });

            modelBuilder.Entity("TrashMob.Models.UserNotification", b =>
                {
                    b.HasOne("TrashMob.Models.User", "CreatedByUser")
                        .WithMany("UserNotificationsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserNotification_CreatedByUser_Id");

                    b.HasOne("TrashMob.Models.Event", "Event")
                        .WithMany("UserNotifications")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_UserNotifications_Event_Id");

                    b.HasOne("TrashMob.Models.User", "LastUpdatedByUser")
                        .WithMany("UserNotificationsUpdated")
                        .HasForeignKey("LastUpdatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserNotification_LastUpdatedByUser_Id");

                    b.HasOne("TrashMob.Models.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserNotifications_User_Id");

                    b.HasOne("TrashMob.Models.UserNotificationType", "UserNotificationType")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserNotificationTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_UserNotifications_UserNotificationTypes");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Event");

                    b.Navigation("LastUpdatedByUser");

                    b.Navigation("User");

                    b.Navigation("UserNotificationType");
                });

            modelBuilder.Entity("TrashMob.Models.Event", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("TrashMob.Models.EventPartnerStatus", b =>
                {
                    b.Navigation("EventPartners");
                });

            modelBuilder.Entity("TrashMob.Models.EventStatus", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TrashMob.Models.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TrashMob.Models.Partner", b =>
                {
                    b.Navigation("PartnerContacts");

                    b.Navigation("PartnerDocuments");

                    b.Navigation("PartnerLocations");

                    b.Navigation("PartnerSocialMediaAccounts");

                    b.Navigation("PartnerUsers");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerRequestStatus", b =>
                {
                    b.Navigation("PartnerRequests");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerStatus", b =>
                {
                    b.Navigation("Partners");
                });

            modelBuilder.Entity("TrashMob.Models.PartnerType", b =>
                {
                    b.Navigation("PartnerRequests");

                    b.Navigation("Partners");
                });

            modelBuilder.Entity("TrashMob.Models.SocialMediaAccountType", b =>
                {
                    b.Navigation("PartnerSocialMediaAccounts");
                });

            modelBuilder.Entity("TrashMob.Models.User", b =>
                {
                    b.Navigation("ContactRequestsCreated");

                    b.Navigation("ContactRequestsUpdated");

                    b.Navigation("EventPartnersCreated");

                    b.Navigation("EventPartnersUpdated");

                    b.Navigation("EventSummariesCreated");

                    b.Navigation("EventSummariesUpdated");

                    b.Navigation("EventsCreated");

                    b.Navigation("EventsUpdated");

                    b.Navigation("MessageRequestsCreated");

                    b.Navigation("MessageRequestsUpdated");

                    b.Navigation("NonEventUserNotifications");

                    b.Navigation("NonEventUserNotificationsCreated");

                    b.Navigation("NonEventUserNotificationsUpdated");

                    b.Navigation("PartnerContactsCreated");

                    b.Navigation("PartnerContactsUpdated");

                    b.Navigation("PartnerDocumentsCreated");

                    b.Navigation("PartnerDocumentsUpdated");

                    b.Navigation("PartnerLocationServicesCreated");

                    b.Navigation("PartnerLocationServicesUpdated");

                    b.Navigation("PartnerLocationsCreated");

                    b.Navigation("PartnerLocationsUpdated");

                    b.Navigation("PartnerRequestsCreated");

                    b.Navigation("PartnerRequestsUpdated");

                    b.Navigation("PartnerServicesCreated");

                    b.Navigation("PartnerServicesUpdated");

                    b.Navigation("PartnerSocialMediaAccountsCreated");

                    b.Navigation("PartnerSocialMediaAccountsUpdated");

                    b.Navigation("PartnerUsersCreated");

                    b.Navigation("PartnerUsersUpdated");

                    b.Navigation("PartnersCreated");

                    b.Navigation("PartnersUpdated");

                    b.Navigation("SiteMetricsCreated");

                    b.Navigation("SiteMetricsUpdated");

                    b.Navigation("UserNotifications");

                    b.Navigation("UserNotificationsCreated");

                    b.Navigation("UserNotificationsUpdated");

                    b.Navigation("UsersCreated");

                    b.Navigation("UsersUpdated");
                });

            modelBuilder.Entity("TrashMob.Models.UserNotificationType", b =>
                {
                    b.Navigation("NonEventUserNotifications");

                    b.Navigation("UserNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
