name: Build Android app

on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
            configuration:
                required: true
                type: string
            build_number:
                required: true
                type: string
            dotnet_version:
                required: true
                type: string
            bundle_id:
                required: true
                type: string
            version:
                required: false
                type: string
        secrets:
            android_keystore:
                required: true
            android_keystore_password:
                required: true
            appsettings:
                required: true
        outputs:
            artifact_name:
                value: artifacts-android-${{ inputs.build_number }}
            bundle_id:
                value: ${{ inputs.bundle_id }}

jobs:
    build:
        runs-on: windows-latest
        environment: ${{ inputs.environment }}
        name: Android Build

        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Install GitVersion
          uses: gittools/actions/gitversion/setup@v1.1.1
          with:
            versionSpec: '5.x'
        
        - name: Determine Version
          id: version_step # step id used as reference for output values
          uses: gittools/actions/gitversion/execute@v1.1.1

        - name: Update Build Number
          run: |
            $content = Get-Content TrashMobMobile/TrashMobMobile.csproj -Raw
            $newContent = $content -replace '<ApplicationVersion>.*</ApplicationVersion>', "<ApplicationVersion>${{ env.BuildMetaData }}</ApplicationVersion>"
            Set-Content TrashMobMobile/TrashMobMobile.csproj -Value $newContent
        
        - name: Update Bundle ID
          run: |
            $content = Get-Content TrashMobMobile/TrashMobMobile.csproj -Raw

            $newContent = $content -replace '<ApplicationId>.*</ApplicationId>', "<ApplicationId>${{ inputs.bundle_id }}</ApplicationId>"

            Set-Content TrashMobMobile/TrashMobMobile.csproj -Value $newContent

        - name: Update version
          run: |
            $content = Get-Content TrashMobMobile/TrashMobMobile.csproj -Raw

            $newContent = $content -replace '<ApplicationDisplayVersion>.*</ApplicationDisplayVersion>', "<ApplicationDisplayVersion>${{ env.semVer }}</ApplicationDisplayVersion>"

            Set-Content TrashMobMobile/TrashMobMobile.csproj -Value $newContent

        - name: Setup DotNet ${{ inputs.dotnet_version }} Environment
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ inputs.dotnet_version }}

        - name: Install MAUI Workload
          run: |
            dotnet nuget locals all --clear
            dotnet workload install maui --ignore-failed-sources
            dotnet workload install android maui wasm-tools --source https://api.nuget.org/v3/index.json

        - name: Restore Dependencies
          run: |
            dotnet restore TrashMobMobileApp.sln

        - name: Publish Android Mobile App
          run: |
            dotnet publish TrashMobMobile/TrashMobMobile.csproj -c:${{ inputs.configuration }} -f:net8.0-android --no-restore /p:AndroidPackageFormat="aab"

        # Store Android Signing Keystore and password in Secrets using base64 encoding
        # https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/certutil
        # command line util to encode to base64 on windows
        - name: Extract Android signing key from env
          shell: bash
          run: |
            cd TrashMobMobile
            mkdir android
            echo "${{ secrets.android_keystore }}" > android/trashmobmobileapp.jks.base64
            base64 -d android/trashmobmobileapp.jks.base64 > android/trashmobmobileapp.decrypted.jks
        # check android SDK paths etc in installed VM : https://github.com/actions/virtual-environments#available-environments
        - name: Sign dev build
          shell: bash
          run: |
            cd TrashMobMobile
            jarsigner -keystore android/trashmobmobileapp.decrypted.jks -storepass "${{ secrets.android_keystore_password }}" -signedjar bin/${{ inputs.configuration }}/net8.0-android/publish/${{ inputs.bundle_id }}-Signed.aab bin/${{ inputs.configuration }}/net8.0-android/publish/${{ inputs.bundle_id }}.aab key

        - uses: actions/upload-artifact@v3.1.2
          with:
            name: artifacts-android-${{ env.semVer }}
            path: |
              TrashMobMobile\bin\${{ inputs.configuration }}\net8.0-android\publish\*.aab
