name: TrashMobMobileApp - Dev

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/main_trashmobmobileapp.yml'
      - '.github/workflows/release_trashmobmobileapp.yml'
      - '.github/workflows/build-android.yml'
      - '.github/workflows/build-ios.yml'
      - '.github/workflows/publish-android.yml'
      - '.github/workflows/publish-ios.yml'
      - 'TrashMob.Models/**'
      - 'TrashMobMobile/**'
  workflow_dispatch:


jobs:
  generate-build-number:
    runs-on: ubuntu-latest
    outputs:
      buildNumber: ${{ steps.set_build_number.outputs.buildNumber }}
      releaseNumber: ${{ steps.set_build_number.outputs.releaseNumber }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.2.1

      - name: Set Offsets
        env:
          NUM: ${{ github.run_number }}
          OFFSET: ${{ steps.version_step.outputs.WeightedPreReleaseNumber }}
        run: |
          GITHUB_RUN_NUMBER_WITH_OFFSET=$(($NUM+$OFFSET))
          echo "GITHUB_RUN_NUMBER_WITH_OFFSET=$(($NUM+$OFFSET))" >> $GITHUB_ENV
          echo "GITHUB_RUN_NUMBER_WITH_OFFSET=$(($NUM+$OFFSET))" >> $GITHUB_OUTPUT

      - name: Set Build Number
        id: set_build_number
        run: |
          buildNumber=${{ steps.version_step.outputs.semVer }}
          releaseNumber=${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}
          echo "buildNumber=${{ steps.version_step.outputs.semVer }}" >> $GITHUB_ENV
          echo "buildNumber=${{ steps.version_step.outputs.semVer }}" >> $GITHUB_OUTPUT
          echo "releaseNumber=${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}" >> $GITHUB_ENV
          echo "releaseNumber=${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}" >> $GITHUB_OUTPUT

  callBuildAndroid:
    name: Call Android build workflow
    needs: [generate-build-number]
    uses: ./.github/workflows/build-android.yml
    with:
      environment: test
      configuration: Release
      build_number: ${{ needs.generate-build-number.outputs.buildNumber }}
      release_number: ${{ needs.generate-build-number.outputs.releaseNumber }}
      dotnet_version: '10.0.x'
      bundle_id: 'eco.trashmobdev.trashmobmobile'
      android_key_name: "upload"
      define_constants: "USETEST"
    secrets: inherit

  calliOSBuild:
    name: Call iOS build workflow
    needs: [generate-build-number]
    uses: ./.github/workflows/build-ios.yml
    with:
      environment: test
      configuration: Release
      build_number: ${{ needs.generate-build-number.outputs.buildNumber }}
      bundle_id: 'eco.trashmobdev.trashmobmobile'
      dotnet_version: '10.0.x'
      ios_provisioning_profile_type: 'IOS_APP_STORE'
      define_constants: "USETEST"
    secrets:
      ios_signing_certificate: ${{ secrets.IOS_CERTIFICATES_P12 }}
      ios_signing_certificate_password: ${{ secrets.IOS_CERTIFICATES_P12_PASSWORD }}
      apple_issuer_id: ${{ secrets.APPSTORE_ISSUER_ID }}
      apple_key_id: ${{ secrets.APPSTORE_KEY_ID }}
      apple_key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
      appsettings: ${{ secrets.MOBILE_APPSETTINGS }}

  callAndroidDeploy:
    name: Call Android deploy workflow
    needs: [callBuildAndroid]
    uses: ./.github/workflows/publish-android.yml
    with:
      artifact_name: ${{ needs.callBuildAndroid.outputs.artifact_name }}
      bundle_id: ${{ needs.callBuildAndroid.outputs.bundle_id }}
      environment: test
    secrets:
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

  calliOSDeploy:
    name: Call iOS deploy workflow
    needs: [calliOSBuild]
    uses: ./.github/workflows/publish-ios.yml
    with:
      artifact_name: ${{ needs.calliOSBuild.outputs.artifact_name }}
      environment: test
    secrets:
      APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
      APPSTORE_API_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
      APPSTORE_API_PRIVATE_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
