# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: TrashMob Mobile App Pull Request Build

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/PullRequest-Mobile.yml'
      - '.github/workflows/build-android.yml'
      - '.github/workflows/build-ios.yml'
      - '.github/workflows/publish-android.yml'
      - '.github/workflows/publish-ios.yml'
      - '.github/workflows/main_trashmobmobileapp.yml'
      - '.github/workflows/release_trashmobmobileapp.yml'
      - 'TrashMob.Models/**'
      - 'TrashMobMobile/**'
      - 'TrashMobMobile.Tests/**'
      - 'TrashMobMobileApp.sln'


jobs:
  generate-build-number:
    runs-on: ubuntu-latest
    outputs:
      buildNumber: ${{ steps.set_build_number.outputs.buildNumber }}
      releaseNumber: ${{ steps.set_build_number.outputs.releaseNumber }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.3.3
        with:
          versionSpec: '5.x'
  
      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v4.3.3

      - name: Set Build Number
        id: set_build_number
        run: |
          buildNumber=${{ steps.version_step.outputs.semVer }}
          releaseNumber=${{ steps.version_step.outputs.WeightedPreReleaseNumber }}
          echo "buildNumber=${{ steps.version_step.outputs.semVer }}" >> $GITHUB_ENV
          echo "buildNumber=${{ steps.version_step.outputs.semVer }}" >> $GITHUB_OUTPUT
          echo "releaseNumber=${{ steps.version_step.outputs.WeightedPreReleaseNumber }}" >> $GITHUB_ENV
          echo "releaseNumber=${{ steps.version_step.outputs.WeightedPreReleaseNumber }}" >> $GITHUB_OUTPUT

  callBuildAndroid:
    name: Call Android build workflow
    needs: [generate-build-number]
    uses: ./.github/workflows/build-android.yml
    with:
      environment: test
      configuration: Release
      build_number: ${{ needs.generate-build-number.outputs.buildNumber }}
      release_number: ${{ needs.generate-build-number.outputs.releaseNumber }}
      dotnet_version: '10.0.x'
      bundle_id: 'eco.trashmobdev.trashmobmobile'
      android_key_name: "upload"
      define_constants: USETEST
    secrets: inherit

  calliOSBuild:
    name: Call iOS build workflow
    needs: [generate-build-number]
    uses: ./.github/workflows/build-ios.yml
    with:
      environment: test
      configuration: Release
      build_number: ${{ needs.generate-build-number.outputs.buildNumber }}
      bundle_id: 'eco.trashmobdev.trashmobmobile'
      dotnet_version: '10.0.x'
      ios_provisioning_profile_type: 'IOS_APP_STORE'
      define_constants: "USETEST"
    secrets:
      ios_signing_certificate: ${{ secrets.IOS_CERTIFICATES_P12 }}
      ios_signing_certificate_password: ${{ secrets.IOS_CERTIFICATES_P12_PASSWORD }}
      apple_issuer_id: ${{ secrets.APPSTORE_ISSUER_ID }}
      apple_key_id: ${{ secrets.APPSTORE_KEY_ID }}
      apple_key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
      appsettings: ${{ secrets.MOBILE_APPSETTINGS }}
